      - name: Extract project
        run: |
          ZIP=$(find . -maxdepth 1 -type f -name "*.zip" | head -n 1)
          echo "Using ZIP: $ZIP"
          unzip -q "$ZIP" -d extracted
          cd extracted/MPDPartnerAndroid
          test -f settings.gradle
          echo "ANDROID_DIR=$(pwd)" >> $GITHUB_ENV
